{{  config(    materialized='view'  )}}

Select ROW_NO,
DATE,
LOCATION,
LOCATION_ISO_CODE,
TOTAL_DEATHS,
TOTAL_DEATHS_PER_MILLION,
TOTAL_CASES,
TOTAL_CASES_PER_MILLION,
NEW_DEATHS,
NEW_DEATHS_PER_MILLION 
FROM {{ ref('covid19') }}